name: Docker Image CI

on:
  pull_request:
    branches: 
      - master
      - staging
      - development
  push:
    branches: 
      - master
      - staging
      - development

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
 #   - uses: actions/checkout@v1
 #   - name: Build the Docker image
 #     run: docker-compose build --pull --build-arg APP_ENV=$APP_ENV
     - name: Setting GITHUB_REF
       env:
         GITHUB_REF: ${{ github.ref}}
       run: echo "GitHub reference = $GITHUB_REF"
     - name: Setting GITHUB_BASE_REF
       env:
         GITHUB_BASE_REF: ${{ github.base_ref }}
       run: echo "GitHub base reference = $GITHUB_BASE_REF"
     - name: Setting APP_ENV
       env:
        APP_ENV: dev
       run: echo "set APP_ENV to $APP_ENV"     
     - if: contains( 'master', GITHUB_REF )
       env:
         APP_ENV: prod
       run: echo "set APP_ENV to $APP_ENV" 
     - if: contains( 'staging', GITHUB_REF )
       env:
         APP_ENV: stag
       run: echo "set APP_ENV to $APP_ENV"  


