name: Docker Image CI

on:
  pull_request:
    branches: 
      - master
      - staging
      - development
  push:
    branches: 
      - master
      - staging
      - development

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
 #   - uses: actions/checkout@v1
 #   - name: Build the Docker image
 #     run: docker-compose build --pull --build-arg APP_ENV=$APP_ENV
     - name: Setting APP_ENV
       env:
        APP_ENV: dev
       run: echo "set APP_ENV to $APP_ENV, GITHUB_REF = $GITHUB_REF"
     - if: contains( github.ref, 'master' )
       env:
         APP_ENV: prod
       run: echo "set APP_ENV to $APP_ENV" 
     - if: contains( github.ref, 'staging' )
       env:
         APP_ENV: stag
       run: echo "set APP_ENV to $APP_ENV"  


