name: Test

on:
    push:
        branches:
            - dev-robert

jobs:

    build:

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Dump folder name
              run: pwd
            - name: Dump folder contents
              run: ls -l
            - name: Export release code
              if: (success() || failure())
              id: releasecode
              run: |
                export BLA=$APP_BUILD-$(git rev-parse --short "$GITHUB_SHA")
                echo $BLA
