name: Test

on:
    push:
        branches:
            - dev-robert

jobs:

    build:

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
            - name: Test if postman files are defined
              id: postmancheck
              run: |
                  if test -f *.postman_collection.json; then 
                    echo "##[set-output name=postmanAvailable]true"
                    echo "true"
                  else
                    echo "##[set-output name=postmanAvailable]false"
                    echo "false"
                  fi
            - name: Install Newman
              if: steps.postmancheck.outputs.postmanAvailable == 'true'
              run: npm install -g newman
            - name: Run Newman
              if: steps.postmancheck.outputs.postmanAvailable == 'true'
              run: newman run *.postman_collection.json
